// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.2
// - protoc             v3.21.12
// source: agent/agent.proto

package agent

import (
	context "context"
	domain "github.com/Hodorev-Evgeny/deploy-guard-service-api/api/domain"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	emptypb "google.golang.org/protobuf/types/known/emptypb"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	AgentService_IndicatorServer_FullMethodName    = "/agent.AgentService/IndicatorServer"
	AgentService_AddProjectInServer_FullMethodName = "/agent.AgentService/AddProjectInServer"
	AgentService_StartProject_FullMethodName       = "/agent.AgentService/StartProject"
	AgentService_StopProject_FullMethodName        = "/agent.AgentService/StopProject"
	AgentService_GetLogsProject_FullMethodName     = "/agent.AgentService/GetLogsProject"
	AgentService_Healthcheck_FullMethodName        = "/agent.AgentService/Healthcheck"
	AgentService_DeployNewVersion_FullMethodName   = "/agent.AgentService/DeployNewVersion"
	AgentService_Rollback_FullMethodName           = "/agent.AgentService/Rollback"
	AgentService_GetStatusProject_FullMethodName   = "/agent.AgentService/GetStatusProject"
	AgentService_GetToken_FullMethodName           = "/agent.AgentService/GetToken"
)

// AgentServiceClient is the client API for AgentService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type AgentServiceClient interface {
	IndicatorServer(ctx context.Context, in *domain.ServerID, opts ...grpc.CallOption) (*domain.MainIndicator, error)
	AddProjectInServer(ctx context.Context, in *RequestAddProject, opts ...grpc.CallOption) (*domain.ResponseProject, error)
	StartProject(ctx context.Context, in *RequestEventProject, opts ...grpc.CallOption) (*domain.ResponseProject, error)
	StopProject(ctx context.Context, in *RequestEventProject, opts ...grpc.CallOption) (*domain.ResponseProject, error)
	GetLogsProject(ctx context.Context, in *domain.LogProjectEnvironment, opts ...grpc.CallOption) (grpc.ServerStreamingClient[LogInformation], error)
	Healthcheck(ctx context.Context, in *RequestEventProject, opts ...grpc.CallOption) (*domain.ResponseProject, error)
	DeployNewVersion(ctx context.Context, in *RequestEventProject, opts ...grpc.CallOption) (*domain.ResponseProject, error)
	Rollback(ctx context.Context, in *RequestEventProject, opts ...grpc.CallOption) (*domain.ResponseProject, error)
	GetStatusProject(ctx context.Context, in *RequestEventProject, opts ...grpc.CallOption) (*domain.ResponseProject, error)
	GetToken(ctx context.Context, in *emptypb.Empty, opts ...grpc.CallOption) (*Token, error)
}

type agentServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewAgentServiceClient(cc grpc.ClientConnInterface) AgentServiceClient {
	return &agentServiceClient{cc}
}

func (c *agentServiceClient) IndicatorServer(ctx context.Context, in *domain.ServerID, opts ...grpc.CallOption) (*domain.MainIndicator, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(domain.MainIndicator)
	err := c.cc.Invoke(ctx, AgentService_IndicatorServer_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *agentServiceClient) AddProjectInServer(ctx context.Context, in *RequestAddProject, opts ...grpc.CallOption) (*domain.ResponseProject, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(domain.ResponseProject)
	err := c.cc.Invoke(ctx, AgentService_AddProjectInServer_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *agentServiceClient) StartProject(ctx context.Context, in *RequestEventProject, opts ...grpc.CallOption) (*domain.ResponseProject, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(domain.ResponseProject)
	err := c.cc.Invoke(ctx, AgentService_StartProject_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *agentServiceClient) StopProject(ctx context.Context, in *RequestEventProject, opts ...grpc.CallOption) (*domain.ResponseProject, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(domain.ResponseProject)
	err := c.cc.Invoke(ctx, AgentService_StopProject_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *agentServiceClient) GetLogsProject(ctx context.Context, in *domain.LogProjectEnvironment, opts ...grpc.CallOption) (grpc.ServerStreamingClient[LogInformation], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &AgentService_ServiceDesc.Streams[0], AgentService_GetLogsProject_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[domain.LogProjectEnvironment, LogInformation]{ClientStream: stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type AgentService_GetLogsProjectClient = grpc.ServerStreamingClient[LogInformation]

func (c *agentServiceClient) Healthcheck(ctx context.Context, in *RequestEventProject, opts ...grpc.CallOption) (*domain.ResponseProject, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(domain.ResponseProject)
	err := c.cc.Invoke(ctx, AgentService_Healthcheck_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *agentServiceClient) DeployNewVersion(ctx context.Context, in *RequestEventProject, opts ...grpc.CallOption) (*domain.ResponseProject, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(domain.ResponseProject)
	err := c.cc.Invoke(ctx, AgentService_DeployNewVersion_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *agentServiceClient) Rollback(ctx context.Context, in *RequestEventProject, opts ...grpc.CallOption) (*domain.ResponseProject, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(domain.ResponseProject)
	err := c.cc.Invoke(ctx, AgentService_Rollback_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *agentServiceClient) GetStatusProject(ctx context.Context, in *RequestEventProject, opts ...grpc.CallOption) (*domain.ResponseProject, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(domain.ResponseProject)
	err := c.cc.Invoke(ctx, AgentService_GetStatusProject_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *agentServiceClient) GetToken(ctx context.Context, in *emptypb.Empty, opts ...grpc.CallOption) (*Token, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Token)
	err := c.cc.Invoke(ctx, AgentService_GetToken_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// AgentServiceServer is the server API for AgentService service.
// All implementations must embed UnimplementedAgentServiceServer
// for forward compatibility.
type AgentServiceServer interface {
	IndicatorServer(context.Context, *domain.ServerID) (*domain.MainIndicator, error)
	AddProjectInServer(context.Context, *RequestAddProject) (*domain.ResponseProject, error)
	StartProject(context.Context, *RequestEventProject) (*domain.ResponseProject, error)
	StopProject(context.Context, *RequestEventProject) (*domain.ResponseProject, error)
	GetLogsProject(*domain.LogProjectEnvironment, grpc.ServerStreamingServer[LogInformation]) error
	Healthcheck(context.Context, *RequestEventProject) (*domain.ResponseProject, error)
	DeployNewVersion(context.Context, *RequestEventProject) (*domain.ResponseProject, error)
	Rollback(context.Context, *RequestEventProject) (*domain.ResponseProject, error)
	GetStatusProject(context.Context, *RequestEventProject) (*domain.ResponseProject, error)
	GetToken(context.Context, *emptypb.Empty) (*Token, error)
	mustEmbedUnimplementedAgentServiceServer()
}

// UnimplementedAgentServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedAgentServiceServer struct{}

func (UnimplementedAgentServiceServer) IndicatorServer(context.Context, *domain.ServerID) (*domain.MainIndicator, error) {
	return nil, status.Error(codes.Unimplemented, "method IndicatorServer not implemented")
}
func (UnimplementedAgentServiceServer) AddProjectInServer(context.Context, *RequestAddProject) (*domain.ResponseProject, error) {
	return nil, status.Error(codes.Unimplemented, "method AddProjectInServer not implemented")
}
func (UnimplementedAgentServiceServer) StartProject(context.Context, *RequestEventProject) (*domain.ResponseProject, error) {
	return nil, status.Error(codes.Unimplemented, "method StartProject not implemented")
}
func (UnimplementedAgentServiceServer) StopProject(context.Context, *RequestEventProject) (*domain.ResponseProject, error) {
	return nil, status.Error(codes.Unimplemented, "method StopProject not implemented")
}
func (UnimplementedAgentServiceServer) GetLogsProject(*domain.LogProjectEnvironment, grpc.ServerStreamingServer[LogInformation]) error {
	return status.Error(codes.Unimplemented, "method GetLogsProject not implemented")
}
func (UnimplementedAgentServiceServer) Healthcheck(context.Context, *RequestEventProject) (*domain.ResponseProject, error) {
	return nil, status.Error(codes.Unimplemented, "method Healthcheck not implemented")
}
func (UnimplementedAgentServiceServer) DeployNewVersion(context.Context, *RequestEventProject) (*domain.ResponseProject, error) {
	return nil, status.Error(codes.Unimplemented, "method DeployNewVersion not implemented")
}
func (UnimplementedAgentServiceServer) Rollback(context.Context, *RequestEventProject) (*domain.ResponseProject, error) {
	return nil, status.Error(codes.Unimplemented, "method Rollback not implemented")
}
func (UnimplementedAgentServiceServer) GetStatusProject(context.Context, *RequestEventProject) (*domain.ResponseProject, error) {
	return nil, status.Error(codes.Unimplemented, "method GetStatusProject not implemented")
}
func (UnimplementedAgentServiceServer) GetToken(context.Context, *emptypb.Empty) (*Token, error) {
	return nil, status.Error(codes.Unimplemented, "method GetToken not implemented")
}
func (UnimplementedAgentServiceServer) mustEmbedUnimplementedAgentServiceServer() {}
func (UnimplementedAgentServiceServer) testEmbeddedByValue()                      {}

// UnsafeAgentServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to AgentServiceServer will
// result in compilation errors.
type UnsafeAgentServiceServer interface {
	mustEmbedUnimplementedAgentServiceServer()
}

func RegisterAgentServiceServer(s grpc.ServiceRegistrar, srv AgentServiceServer) {
	// If the following call panics, it indicates UnimplementedAgentServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&AgentService_ServiceDesc, srv)
}

func _AgentService_IndicatorServer_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(domain.ServerID)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AgentServiceServer).IndicatorServer(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AgentService_IndicatorServer_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AgentServiceServer).IndicatorServer(ctx, req.(*domain.ServerID))
	}
	return interceptor(ctx, in, info, handler)
}

func _AgentService_AddProjectInServer_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RequestAddProject)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AgentServiceServer).AddProjectInServer(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AgentService_AddProjectInServer_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AgentServiceServer).AddProjectInServer(ctx, req.(*RequestAddProject))
	}
	return interceptor(ctx, in, info, handler)
}

func _AgentService_StartProject_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RequestEventProject)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AgentServiceServer).StartProject(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AgentService_StartProject_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AgentServiceServer).StartProject(ctx, req.(*RequestEventProject))
	}
	return interceptor(ctx, in, info, handler)
}

func _AgentService_StopProject_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RequestEventProject)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AgentServiceServer).StopProject(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AgentService_StopProject_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AgentServiceServer).StopProject(ctx, req.(*RequestEventProject))
	}
	return interceptor(ctx, in, info, handler)
}

func _AgentService_GetLogsProject_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(domain.LogProjectEnvironment)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(AgentServiceServer).GetLogsProject(m, &grpc.GenericServerStream[domain.LogProjectEnvironment, LogInformation]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type AgentService_GetLogsProjectServer = grpc.ServerStreamingServer[LogInformation]

func _AgentService_Healthcheck_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RequestEventProject)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AgentServiceServer).Healthcheck(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AgentService_Healthcheck_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AgentServiceServer).Healthcheck(ctx, req.(*RequestEventProject))
	}
	return interceptor(ctx, in, info, handler)
}

func _AgentService_DeployNewVersion_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RequestEventProject)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AgentServiceServer).DeployNewVersion(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AgentService_DeployNewVersion_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AgentServiceServer).DeployNewVersion(ctx, req.(*RequestEventProject))
	}
	return interceptor(ctx, in, info, handler)
}

func _AgentService_Rollback_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RequestEventProject)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AgentServiceServer).Rollback(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AgentService_Rollback_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AgentServiceServer).Rollback(ctx, req.(*RequestEventProject))
	}
	return interceptor(ctx, in, info, handler)
}

func _AgentService_GetStatusProject_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RequestEventProject)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AgentServiceServer).GetStatusProject(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AgentService_GetStatusProject_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AgentServiceServer).GetStatusProject(ctx, req.(*RequestEventProject))
	}
	return interceptor(ctx, in, info, handler)
}

func _AgentService_GetToken_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(emptypb.Empty)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AgentServiceServer).GetToken(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AgentService_GetToken_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AgentServiceServer).GetToken(ctx, req.(*emptypb.Empty))
	}
	return interceptor(ctx, in, info, handler)
}

// AgentService_ServiceDesc is the grpc.ServiceDesc for AgentService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var AgentService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "agent.AgentService",
	HandlerType: (*AgentServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "IndicatorServer",
			Handler:    _AgentService_IndicatorServer_Handler,
		},
		{
			MethodName: "AddProjectInServer",
			Handler:    _AgentService_AddProjectInServer_Handler,
		},
		{
			MethodName: "StartProject",
			Handler:    _AgentService_StartProject_Handler,
		},
		{
			MethodName: "StopProject",
			Handler:    _AgentService_StopProject_Handler,
		},
		{
			MethodName: "Healthcheck",
			Handler:    _AgentService_Healthcheck_Handler,
		},
		{
			MethodName: "DeployNewVersion",
			Handler:    _AgentService_DeployNewVersion_Handler,
		},
		{
			MethodName: "Rollback",
			Handler:    _AgentService_Rollback_Handler,
		},
		{
			MethodName: "GetStatusProject",
			Handler:    _AgentService_GetStatusProject_Handler,
		},
		{
			MethodName: "GetToken",
			Handler:    _AgentService_GetToken_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "GetLogsProject",
			Handler:       _AgentService_GetLogsProject_Handler,
			ServerStreams: true,
		},
	},
	Metadata: "agent/agent.proto",
}
