// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v3.21.12
// source: agent/agent.proto

package agent

import (
	domain "github.com/Hodorev-Evgeny/deploy-guard-service-grpc/api/domain"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	emptypb "google.golang.org/protobuf/types/known/emptypb"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type RequestAddProject struct {
	state              protoimpl.MessageState     `protogen:"open.v1"`
	ProjectEnvironment *domain.ProjectEnvironment `protobuf:"bytes,1,opt,name=project_environment,json=projectEnvironment,proto3" json:"project_environment,omitempty"`
	ServerId           *domain.ServerID           `protobuf:"bytes,2,opt,name=server_id,json=serverId,proto3" json:"server_id,omitempty"`
	unknownFields      protoimpl.UnknownFields
	sizeCache          protoimpl.SizeCache
}

func (x *RequestAddProject) Reset() {
	*x = RequestAddProject{}
	mi := &file_agent_agent_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RequestAddProject) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RequestAddProject) ProtoMessage() {}

func (x *RequestAddProject) ProtoReflect() protoreflect.Message {
	mi := &file_agent_agent_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RequestAddProject.ProtoReflect.Descriptor instead.
func (*RequestAddProject) Descriptor() ([]byte, []int) {
	return file_agent_agent_proto_rawDescGZIP(), []int{0}
}

func (x *RequestAddProject) GetProjectEnvironment() *domain.ProjectEnvironment {
	if x != nil {
		return x.ProjectEnvironment
	}
	return nil
}

func (x *RequestAddProject) GetServerId() *domain.ServerID {
	if x != nil {
		return x.ServerId
	}
	return nil
}

type RequestEventProject struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ProjectId     *domain.ProjectID      `protobuf:"bytes,1,opt,name=project_id,json=projectId,proto3" json:"project_id,omitempty"`
	ServerId      *domain.ServerID       `protobuf:"bytes,2,opt,name=server_id,json=serverId,proto3" json:"server_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RequestEventProject) Reset() {
	*x = RequestEventProject{}
	mi := &file_agent_agent_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RequestEventProject) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RequestEventProject) ProtoMessage() {}

func (x *RequestEventProject) ProtoReflect() protoreflect.Message {
	mi := &file_agent_agent_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RequestEventProject.ProtoReflect.Descriptor instead.
func (*RequestEventProject) Descriptor() ([]byte, []int) {
	return file_agent_agent_proto_rawDescGZIP(), []int{1}
}

func (x *RequestEventProject) GetProjectId() *domain.ProjectID {
	if x != nil {
		return x.ProjectId
	}
	return nil
}

func (x *RequestEventProject) GetServerId() *domain.ServerID {
	if x != nil {
		return x.ServerId
	}
	return nil
}

type LogInformation struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ProjectId     *domain.ProjectID      `protobuf:"bytes,1,opt,name=project_id,json=projectId,proto3" json:"project_id,omitempty"`
	LogInfo       string                 `protobuf:"bytes,2,opt,name=log_info,json=logInfo,proto3" json:"log_info,omitempty"`
	DateLog       *timestamppb.Timestamp `protobuf:"bytes,3,opt,name=date_log,json=dateLog,proto3" json:"date_log,omitempty"`
	Source        string                 `protobuf:"bytes,4,opt,name=source,proto3" json:"source,omitempty"`
	HasError      bool                   `protobuf:"varint,5,opt,name=has_error,json=hasError,proto3" json:"has_error,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LogInformation) Reset() {
	*x = LogInformation{}
	mi := &file_agent_agent_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LogInformation) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LogInformation) ProtoMessage() {}

func (x *LogInformation) ProtoReflect() protoreflect.Message {
	mi := &file_agent_agent_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LogInformation.ProtoReflect.Descriptor instead.
func (*LogInformation) Descriptor() ([]byte, []int) {
	return file_agent_agent_proto_rawDescGZIP(), []int{2}
}

func (x *LogInformation) GetProjectId() *domain.ProjectID {
	if x != nil {
		return x.ProjectId
	}
	return nil
}

func (x *LogInformation) GetLogInfo() string {
	if x != nil {
		return x.LogInfo
	}
	return ""
}

func (x *LogInformation) GetDateLog() *timestamppb.Timestamp {
	if x != nil {
		return x.DateLog
	}
	return nil
}

func (x *LogInformation) GetSource() string {
	if x != nil {
		return x.Source
	}
	return ""
}

func (x *LogInformation) GetHasError() bool {
	if x != nil {
		return x.HasError
	}
	return false
}

type Token struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TokenServer   string                 `protobuf:"bytes,1,opt,name=token_server,json=tokenServer,proto3" json:"token_server,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Token) Reset() {
	*x = Token{}
	mi := &file_agent_agent_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Token) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Token) ProtoMessage() {}

func (x *Token) ProtoReflect() protoreflect.Message {
	mi := &file_agent_agent_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Token.ProtoReflect.Descriptor instead.
func (*Token) Descriptor() ([]byte, []int) {
	return file_agent_agent_proto_rawDescGZIP(), []int{3}
}

func (x *Token) GetTokenServer() string {
	if x != nil {
		return x.TokenServer
	}
	return ""
}

var File_agent_agent_proto protoreflect.FileDescriptor

const file_agent_agent_proto_rawDesc = "" +
	"\n" +
	"\x11agent/agent.proto\x12\x05agent\x1a\x13domain/server.proto\x1a\x1bgoogle/protobuf/empty.proto\x1a\x1fgoogle/protobuf/timestamp.proto\x1a\x14domain/project.proto\"\x8f\x01\n" +
	"\x11RequestAddProject\x12K\n" +
	"\x13project_environment\x18\x01 \x01(\v2\x1a.domain.ProjectEnvironmentR\x12projectEnvironment\x12-\n" +
	"\tserver_id\x18\x02 \x01(\v2\x10.domain.ServerIDR\bserverId\"v\n" +
	"\x13RequestEventProject\x120\n" +
	"\n" +
	"project_id\x18\x01 \x01(\v2\x11.domain.ProjectIDR\tprojectId\x12-\n" +
	"\tserver_id\x18\x02 \x01(\v2\x10.domain.ServerIDR\bserverId\"\xc9\x01\n" +
	"\x0eLogInformation\x120\n" +
	"\n" +
	"project_id\x18\x01 \x01(\v2\x11.domain.ProjectIDR\tprojectId\x12\x19\n" +
	"\blog_info\x18\x02 \x01(\tR\alogInfo\x125\n" +
	"\bdate_log\x18\x03 \x01(\v2\x1a.google.protobuf.TimestampR\adateLog\x12\x16\n" +
	"\x06source\x18\x04 \x01(\tR\x06source\x12\x1b\n" +
	"\thas_error\x18\x05 \x01(\bR\bhasError\"*\n" +
	"\x05Token\x12!\n" +
	"\ftoken_server\x18\x01 \x01(\tR\vtokenServer2\xc3\x05\n" +
	"\fAgentService\x12<\n" +
	"\x0fIndicatorServer\x12\x10.domain.ServerID\x1a\x15.domain.MainIndicator\"\x00\x12I\n" +
	"\x12AddProjectInServer\x12\x18.agent.RequestAddProject\x1a\x17.domain.ResponseProject\"\x00\x12E\n" +
	"\fStartProject\x12\x1a.agent.RequestEventProject\x1a\x17.domain.ResponseProject\"\x00\x12D\n" +
	"\vStopProject\x12\x1a.agent.RequestEventProject\x1a\x17.domain.ResponseProject\"\x00\x12J\n" +
	"\x0eGetLogsProject\x12\x1d.domain.LogProjectEnvironment\x1a\x15.agent.LogInformation\"\x000\x01\x12D\n" +
	"\vHealthcheck\x12\x1a.agent.RequestEventProject\x1a\x17.domain.ResponseProject\"\x00\x12I\n" +
	"\x10DeployNewVersion\x12\x1a.agent.RequestEventProject\x1a\x17.domain.ResponseProject\"\x00\x12A\n" +
	"\bRollback\x12\x1a.agent.RequestEventProject\x1a\x17.domain.ResponseProject\"\x00\x12I\n" +
	"\x10GetStatusProject\x12\x1a.agent.RequestEventProject\x1a\x17.domain.ResponseProject\"\x00\x122\n" +
	"\bGetToken\x12\x16.google.protobuf.Empty\x1a\f.agent.Token\"\x00BEZCgithub.com/Hodorev-Evgeny/deploy-guard-service-grpc/api/agent;agentb\x06proto3"

var (
	file_agent_agent_proto_rawDescOnce sync.Once
	file_agent_agent_proto_rawDescData []byte
)

func file_agent_agent_proto_rawDescGZIP() []byte {
	file_agent_agent_proto_rawDescOnce.Do(func() {
		file_agent_agent_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_agent_agent_proto_rawDesc), len(file_agent_agent_proto_rawDesc)))
	})
	return file_agent_agent_proto_rawDescData
}

var file_agent_agent_proto_msgTypes = make([]protoimpl.MessageInfo, 4)
var file_agent_agent_proto_goTypes = []any{
	(*RequestAddProject)(nil),            // 0: agent.RequestAddProject
	(*RequestEventProject)(nil),          // 1: agent.RequestEventProject
	(*LogInformation)(nil),               // 2: agent.LogInformation
	(*Token)(nil),                        // 3: agent.Token
	(*domain.ProjectEnvironment)(nil),    // 4: domain.ProjectEnvironment
	(*domain.ServerID)(nil),              // 5: domain.ServerID
	(*domain.ProjectID)(nil),             // 6: domain.ProjectID
	(*timestamppb.Timestamp)(nil),        // 7: google.protobuf.Timestamp
	(*domain.LogProjectEnvironment)(nil), // 8: domain.LogProjectEnvironment
	(*emptypb.Empty)(nil),                // 9: google.protobuf.Empty
	(*domain.MainIndicator)(nil),         // 10: domain.MainIndicator
	(*domain.ResponseProject)(nil),       // 11: domain.ResponseProject
}
var file_agent_agent_proto_depIdxs = []int32{
	4,  // 0: agent.RequestAddProject.project_environment:type_name -> domain.ProjectEnvironment
	5,  // 1: agent.RequestAddProject.server_id:type_name -> domain.ServerID
	6,  // 2: agent.RequestEventProject.project_id:type_name -> domain.ProjectID
	5,  // 3: agent.RequestEventProject.server_id:type_name -> domain.ServerID
	6,  // 4: agent.LogInformation.project_id:type_name -> domain.ProjectID
	7,  // 5: agent.LogInformation.date_log:type_name -> google.protobuf.Timestamp
	5,  // 6: agent.AgentService.IndicatorServer:input_type -> domain.ServerID
	0,  // 7: agent.AgentService.AddProjectInServer:input_type -> agent.RequestAddProject
	1,  // 8: agent.AgentService.StartProject:input_type -> agent.RequestEventProject
	1,  // 9: agent.AgentService.StopProject:input_type -> agent.RequestEventProject
	8,  // 10: agent.AgentService.GetLogsProject:input_type -> domain.LogProjectEnvironment
	1,  // 11: agent.AgentService.Healthcheck:input_type -> agent.RequestEventProject
	1,  // 12: agent.AgentService.DeployNewVersion:input_type -> agent.RequestEventProject
	1,  // 13: agent.AgentService.Rollback:input_type -> agent.RequestEventProject
	1,  // 14: agent.AgentService.GetStatusProject:input_type -> agent.RequestEventProject
	9,  // 15: agent.AgentService.GetToken:input_type -> google.protobuf.Empty
	10, // 16: agent.AgentService.IndicatorServer:output_type -> domain.MainIndicator
	11, // 17: agent.AgentService.AddProjectInServer:output_type -> domain.ResponseProject
	11, // 18: agent.AgentService.StartProject:output_type -> domain.ResponseProject
	11, // 19: agent.AgentService.StopProject:output_type -> domain.ResponseProject
	2,  // 20: agent.AgentService.GetLogsProject:output_type -> agent.LogInformation
	11, // 21: agent.AgentService.Healthcheck:output_type -> domain.ResponseProject
	11, // 22: agent.AgentService.DeployNewVersion:output_type -> domain.ResponseProject
	11, // 23: agent.AgentService.Rollback:output_type -> domain.ResponseProject
	11, // 24: agent.AgentService.GetStatusProject:output_type -> domain.ResponseProject
	3,  // 25: agent.AgentService.GetToken:output_type -> agent.Token
	16, // [16:26] is the sub-list for method output_type
	6,  // [6:16] is the sub-list for method input_type
	6,  // [6:6] is the sub-list for extension type_name
	6,  // [6:6] is the sub-list for extension extendee
	0,  // [0:6] is the sub-list for field type_name
}

func init() { file_agent_agent_proto_init() }
func file_agent_agent_proto_init() {
	if File_agent_agent_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_agent_agent_proto_rawDesc), len(file_agent_agent_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   4,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_agent_agent_proto_goTypes,
		DependencyIndexes: file_agent_agent_proto_depIdxs,
		MessageInfos:      file_agent_agent_proto_msgTypes,
	}.Build()
	File_agent_agent_proto = out.File
	file_agent_agent_proto_goTypes = nil
	file_agent_agent_proto_depIdxs = nil
}
