syntax = "proto3";

package agent;

option go_package = "github.com/Hodorev-Evgeny/deploy-guard-service-api/api/agent;agent";

import "domain/server.proto";
import "google/protobuf/empty.proto";
import "google/protobuf/timestamp.proto";
import "domain/project.proto";


service AgentService {
  rpc IndicatorServer(domain.ServerID) returns (domain.MainIndicator) {}

  rpc AddProjectInServer(RequestAddProject) returns (domain.ResponseProject) {}

  rpc StartProject(RequestEventProject) returns (domain.ResponseProject) {}

  rpc StopProject(RequestEventProject) returns (domain.ResponseProject) {}

  rpc GetLogsProject(domain.LogProjectEnvironment) returns (stream LogInformation) {}

  rpc Healthcheck(RequestEventProject) returns (domain.ResponseProject) {}

  rpc DeployNewVersion(RequestEventProject) returns (domain.ResponseProject) {}

  rpc Rollback(RequestEventProject) returns (domain.ResponseProject) {}

  rpc GetStatusProject(RequestEventProject) returns (domain.ResponseProject) {}

  rpc GetToken(google.protobuf.Empty) returns (Token) {}
}

message RequestAddProject {
  domain.ProjectEnvironment project_environment = 1;
  domain.ServerID server_id = 2;
}

message RequestEventProject {
  domain.ProjectID project_id = 1;
  domain.ServerID server_id = 2;
}

message LogInformation {
  domain.ProjectID project_id = 1;
  string log_info = 2;
  google.protobuf.Timestamp date_log = 3;
  string source = 4;
  bool has_error = 5;
}

message Token {
  string token_server = 1;
}