// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v3.21.12
// source: domain/project.proto

package domain

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type ProjectStatus int32

const (
	ProjectStatus_PROJECT_STATUS_UNSPECIFIED ProjectStatus = 0
	ProjectStatus_PROJECT_STATUS_RUNNING     ProjectStatus = 1
	ProjectStatus_PROJECT_STATUS_STOPPED     ProjectStatus = 2
	ProjectStatus_PROJECT_STATUS_DEPLOYING   ProjectStatus = 3
	ProjectStatus_PROJECT_STATUS_FAILED      ProjectStatus = 4
	ProjectStatus_PROJECT_STATUS_UNKNOWN     ProjectStatus = 5
	ProjectStatus_PROJECT_STATUS_ROLLBACK    ProjectStatus = 6
)

// Enum value maps for ProjectStatus.
var (
	ProjectStatus_name = map[int32]string{
		0: "PROJECT_STATUS_UNSPECIFIED",
		1: "PROJECT_STATUS_RUNNING",
		2: "PROJECT_STATUS_STOPPED",
		3: "PROJECT_STATUS_DEPLOYING",
		4: "PROJECT_STATUS_FAILED",
		5: "PROJECT_STATUS_UNKNOWN",
		6: "PROJECT_STATUS_ROLLBACK",
	}
	ProjectStatus_value = map[string]int32{
		"PROJECT_STATUS_UNSPECIFIED": 0,
		"PROJECT_STATUS_RUNNING":     1,
		"PROJECT_STATUS_STOPPED":     2,
		"PROJECT_STATUS_DEPLOYING":   3,
		"PROJECT_STATUS_FAILED":      4,
		"PROJECT_STATUS_UNKNOWN":     5,
		"PROJECT_STATUS_ROLLBACK":    6,
	}
)

func (x ProjectStatus) Enum() *ProjectStatus {
	p := new(ProjectStatus)
	*p = x
	return p
}

func (x ProjectStatus) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (ProjectStatus) Descriptor() protoreflect.EnumDescriptor {
	return file_domain_project_proto_enumTypes[0].Descriptor()
}

func (ProjectStatus) Type() protoreflect.EnumType {
	return &file_domain_project_proto_enumTypes[0]
}

func (x ProjectStatus) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use ProjectStatus.Descriptor instead.
func (ProjectStatus) EnumDescriptor() ([]byte, []int) {
	return file_domain_project_proto_rawDescGZIP(), []int{0}
}

type ProjectID struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int64                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ProjectID) Reset() {
	*x = ProjectID{}
	mi := &file_domain_project_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ProjectID) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ProjectID) ProtoMessage() {}

func (x *ProjectID) ProtoReflect() protoreflect.Message {
	mi := &file_domain_project_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ProjectID.ProtoReflect.Descriptor instead.
func (*ProjectID) Descriptor() ([]byte, []int) {
	return file_domain_project_proto_rawDescGZIP(), []int{0}
}

func (x *ProjectID) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

type ResponseProject struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	NameProject   string                 `protobuf:"bytes,1,opt,name=name_project,json=nameProject,proto3" json:"name_project,omitempty"`
	ProjectId     *ProjectID             `protobuf:"bytes,2,opt,name=project_id,json=projectId,proto3" json:"project_id,omitempty"`
	TimeEvent     *timestamppb.Timestamp `protobuf:"bytes,3,opt,name=time_event,json=timeEvent,proto3" json:"time_event,omitempty"`
	Status        ProjectStatus          `protobuf:"varint,4,opt,name=status,proto3,enum=domain.ProjectStatus" json:"status,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ResponseProject) Reset() {
	*x = ResponseProject{}
	mi := &file_domain_project_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ResponseProject) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ResponseProject) ProtoMessage() {}

func (x *ResponseProject) ProtoReflect() protoreflect.Message {
	mi := &file_domain_project_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ResponseProject.ProtoReflect.Descriptor instead.
func (*ResponseProject) Descriptor() ([]byte, []int) {
	return file_domain_project_proto_rawDescGZIP(), []int{1}
}

func (x *ResponseProject) GetNameProject() string {
	if x != nil {
		return x.NameProject
	}
	return ""
}

func (x *ResponseProject) GetProjectId() *ProjectID {
	if x != nil {
		return x.ProjectId
	}
	return nil
}

func (x *ResponseProject) GetTimeEvent() *timestamppb.Timestamp {
	if x != nil {
		return x.TimeEvent
	}
	return nil
}

func (x *ResponseProject) GetStatus() ProjectStatus {
	if x != nil {
		return x.Status
	}
	return ProjectStatus_PROJECT_STATUS_UNSPECIFIED
}

type ProjectEnvironment struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	PathGithub    string                 `protobuf:"bytes,1,opt,name=path_github,json=pathGithub,proto3" json:"path_github,omitempty"`
	Branch        string                 `protobuf:"bytes,2,opt,name=branch,proto3" json:"branch,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ProjectEnvironment) Reset() {
	*x = ProjectEnvironment{}
	mi := &file_domain_project_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ProjectEnvironment) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ProjectEnvironment) ProtoMessage() {}

func (x *ProjectEnvironment) ProtoReflect() protoreflect.Message {
	mi := &file_domain_project_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ProjectEnvironment.ProtoReflect.Descriptor instead.
func (*ProjectEnvironment) Descriptor() ([]byte, []int) {
	return file_domain_project_proto_rawDescGZIP(), []int{2}
}

func (x *ProjectEnvironment) GetPathGithub() string {
	if x != nil {
		return x.PathGithub
	}
	return ""
}

func (x *ProjectEnvironment) GetBranch() string {
	if x != nil {
		return x.Branch
	}
	return ""
}

type LogProjectEnvironment struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ProjectId     *ProjectID             `protobuf:"bytes,1,opt,name=project_id,json=projectId,proto3" json:"project_id,omitempty"`
	ServerId      *ServerID              `protobuf:"bytes,2,opt,name=server_id,json=serverId,proto3" json:"server_id,omitempty"`
	Path          string                 `protobuf:"bytes,3,opt,name=path,proto3" json:"path,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LogProjectEnvironment) Reset() {
	*x = LogProjectEnvironment{}
	mi := &file_domain_project_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LogProjectEnvironment) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LogProjectEnvironment) ProtoMessage() {}

func (x *LogProjectEnvironment) ProtoReflect() protoreflect.Message {
	mi := &file_domain_project_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LogProjectEnvironment.ProtoReflect.Descriptor instead.
func (*LogProjectEnvironment) Descriptor() ([]byte, []int) {
	return file_domain_project_proto_rawDescGZIP(), []int{3}
}

func (x *LogProjectEnvironment) GetProjectId() *ProjectID {
	if x != nil {
		return x.ProjectId
	}
	return nil
}

func (x *LogProjectEnvironment) GetServerId() *ServerID {
	if x != nil {
		return x.ServerId
	}
	return nil
}

func (x *LogProjectEnvironment) GetPath() string {
	if x != nil {
		return x.Path
	}
	return ""
}

var File_domain_project_proto protoreflect.FileDescriptor

const file_domain_project_proto_rawDesc = "" +
	"\n" +
	"\x14domain/project.proto\x12\x06domain\x1a\x1fgoogle/protobuf/timestamp.proto\x1a\x13domain/server.proto\"\x1b\n" +
	"\tProjectID\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id\"\xd0\x01\n" +
	"\x0fResponseProject\x12!\n" +
	"\fname_project\x18\x01 \x01(\tR\vnameProject\x120\n" +
	"\n" +
	"project_id\x18\x02 \x01(\v2\x11.domain.ProjectIDR\tprojectId\x129\n" +
	"\n" +
	"time_event\x18\x03 \x01(\v2\x1a.google.protobuf.TimestampR\ttimeEvent\x12-\n" +
	"\x06status\x18\x04 \x01(\x0e2\x15.domain.ProjectStatusR\x06status\"M\n" +
	"\x12ProjectEnvironment\x12\x1f\n" +
	"\vpath_github\x18\x01 \x01(\tR\n" +
	"pathGithub\x12\x16\n" +
	"\x06branch\x18\x02 \x01(\tR\x06branch\"\x8c\x01\n" +
	"\x15LogProjectEnvironment\x120\n" +
	"\n" +
	"project_id\x18\x01 \x01(\v2\x11.domain.ProjectIDR\tprojectId\x12-\n" +
	"\tserver_id\x18\x02 \x01(\v2\x10.domain.ServerIDR\bserverId\x12\x12\n" +
	"\x04path\x18\x03 \x01(\tR\x04path*\xd9\x01\n" +
	"\rProjectStatus\x12\x1e\n" +
	"\x1aPROJECT_STATUS_UNSPECIFIED\x10\x00\x12\x1a\n" +
	"\x16PROJECT_STATUS_RUNNING\x10\x01\x12\x1a\n" +
	"\x16PROJECT_STATUS_STOPPED\x10\x02\x12\x1c\n" +
	"\x18PROJECT_STATUS_DEPLOYING\x10\x03\x12\x19\n" +
	"\x15PROJECT_STATUS_FAILED\x10\x04\x12\x1a\n" +
	"\x16PROJECT_STATUS_UNKNOWN\x10\x05\x12\x1b\n" +
	"\x17PROJECT_STATUS_ROLLBACK\x10\x06BFZDgithub.com/Hodorev-Evgeny/deploy-guard-service-api/api/domain;domainb\x06proto3"

var (
	file_domain_project_proto_rawDescOnce sync.Once
	file_domain_project_proto_rawDescData []byte
)

func file_domain_project_proto_rawDescGZIP() []byte {
	file_domain_project_proto_rawDescOnce.Do(func() {
		file_domain_project_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_domain_project_proto_rawDesc), len(file_domain_project_proto_rawDesc)))
	})
	return file_domain_project_proto_rawDescData
}

var file_domain_project_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_domain_project_proto_msgTypes = make([]protoimpl.MessageInfo, 4)
var file_domain_project_proto_goTypes = []any{
	(ProjectStatus)(0),            // 0: domain.ProjectStatus
	(*ProjectID)(nil),             // 1: domain.ProjectID
	(*ResponseProject)(nil),       // 2: domain.ResponseProject
	(*ProjectEnvironment)(nil),    // 3: domain.ProjectEnvironment
	(*LogProjectEnvironment)(nil), // 4: domain.LogProjectEnvironment
	(*timestamppb.Timestamp)(nil), // 5: google.protobuf.Timestamp
	(*ServerID)(nil),              // 6: domain.ServerID
}
var file_domain_project_proto_depIdxs = []int32{
	1, // 0: domain.ResponseProject.project_id:type_name -> domain.ProjectID
	5, // 1: domain.ResponseProject.time_event:type_name -> google.protobuf.Timestamp
	0, // 2: domain.ResponseProject.status:type_name -> domain.ProjectStatus
	1, // 3: domain.LogProjectEnvironment.project_id:type_name -> domain.ProjectID
	6, // 4: domain.LogProjectEnvironment.server_id:type_name -> domain.ServerID
	5, // [5:5] is the sub-list for method output_type
	5, // [5:5] is the sub-list for method input_type
	5, // [5:5] is the sub-list for extension type_name
	5, // [5:5] is the sub-list for extension extendee
	0, // [0:5] is the sub-list for field type_name
}

func init() { file_domain_project_proto_init() }
func file_domain_project_proto_init() {
	if File_domain_project_proto != nil {
		return
	}
	file_domain_server_proto_init()
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_domain_project_proto_rawDesc), len(file_domain_project_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   4,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_domain_project_proto_goTypes,
		DependencyIndexes: file_domain_project_proto_depIdxs,
		EnumInfos:         file_domain_project_proto_enumTypes,
		MessageInfos:      file_domain_project_proto_msgTypes,
	}.Build()
	File_domain_project_proto = out.File
	file_domain_project_proto_goTypes = nil
	file_domain_project_proto_depIdxs = nil
}
