// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v3.21.12
// source: domain/server.proto

package domain

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type ServerStatus int32

const (
	ServerStatus_SERVER_STATUS_UNSPECIFIED ServerStatus = 0
	ServerStatus_SERVER_STATUS_ONLINE      ServerStatus = 1
	ServerStatus_SERVER_STATUS_OFFLINE     ServerStatus = 2
	ServerStatus_SERVER_STATUS_WARNING     ServerStatus = 3
	ServerStatus_SERVER_STATUS_UNKNOWN     ServerStatus = 4
	ServerStatus_SERVER_STATUS_DISABLED    ServerStatus = 5
)

// Enum value maps for ServerStatus.
var (
	ServerStatus_name = map[int32]string{
		0: "SERVER_STATUS_UNSPECIFIED",
		1: "SERVER_STATUS_ONLINE",
		2: "SERVER_STATUS_OFFLINE",
		3: "SERVER_STATUS_WARNING",
		4: "SERVER_STATUS_UNKNOWN",
		5: "SERVER_STATUS_DISABLED",
	}
	ServerStatus_value = map[string]int32{
		"SERVER_STATUS_UNSPECIFIED": 0,
		"SERVER_STATUS_ONLINE":      1,
		"SERVER_STATUS_OFFLINE":     2,
		"SERVER_STATUS_WARNING":     3,
		"SERVER_STATUS_UNKNOWN":     4,
		"SERVER_STATUS_DISABLED":    5,
	}
)

func (x ServerStatus) Enum() *ServerStatus {
	p := new(ServerStatus)
	*p = x
	return p
}

func (x ServerStatus) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (ServerStatus) Descriptor() protoreflect.EnumDescriptor {
	return file_domain_server_proto_enumTypes[0].Descriptor()
}

func (ServerStatus) Type() protoreflect.EnumType {
	return &file_domain_server_proto_enumTypes[0]
}

func (x ServerStatus) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use ServerStatus.Descriptor instead.
func (ServerStatus) EnumDescriptor() ([]byte, []int) {
	return file_domain_server_proto_rawDescGZIP(), []int{0}
}

type ServerID struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int64                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ServerID) Reset() {
	*x = ServerID{}
	mi := &file_domain_server_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ServerID) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ServerID) ProtoMessage() {}

func (x *ServerID) ProtoReflect() protoreflect.Message {
	mi := &file_domain_server_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ServerID.ProtoReflect.Descriptor instead.
func (*ServerID) Descriptor() ([]byte, []int) {
	return file_domain_server_proto_rawDescGZIP(), []int{0}
}

func (x *ServerID) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

type MainIndicator struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	NameServer    string                 `protobuf:"bytes,1,opt,name=name_server,json=nameServer,proto3" json:"name_server,omitempty"`
	Status        ServerStatus           `protobuf:"varint,2,opt,name=status,proto3,enum=domain.ServerStatus" json:"status,omitempty"`
	LastConnect   *timestamppb.Timestamp `protobuf:"bytes,3,opt,name=last_connect,json=lastConnect,proto3" json:"last_connect,omitempty"`
	CpuUsed       float32                `protobuf:"fixed32,4,opt,name=cpu_used,json=cpuUsed,proto3" json:"cpu_used,omitempty"`
	RamUsed       float32                `protobuf:"fixed32,5,opt,name=ram_used,json=ramUsed,proto3" json:"ram_used,omitempty"`
	DiskUsed      float32                `protobuf:"fixed32,6,opt,name=disk_used,json=diskUsed,proto3" json:"disk_used,omitempty"`
	CountProject  int64                  `protobuf:"varint,7,opt,name=count_project,json=countProject,proto3" json:"count_project,omitempty"`
	CountProblem  int64                  `protobuf:"varint,8,opt,name=count_problem,json=countProblem,proto3" json:"count_problem,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MainIndicator) Reset() {
	*x = MainIndicator{}
	mi := &file_domain_server_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MainIndicator) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MainIndicator) ProtoMessage() {}

func (x *MainIndicator) ProtoReflect() protoreflect.Message {
	mi := &file_domain_server_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MainIndicator.ProtoReflect.Descriptor instead.
func (*MainIndicator) Descriptor() ([]byte, []int) {
	return file_domain_server_proto_rawDescGZIP(), []int{1}
}

func (x *MainIndicator) GetNameServer() string {
	if x != nil {
		return x.NameServer
	}
	return ""
}

func (x *MainIndicator) GetStatus() ServerStatus {
	if x != nil {
		return x.Status
	}
	return ServerStatus_SERVER_STATUS_UNSPECIFIED
}

func (x *MainIndicator) GetLastConnect() *timestamppb.Timestamp {
	if x != nil {
		return x.LastConnect
	}
	return nil
}

func (x *MainIndicator) GetCpuUsed() float32 {
	if x != nil {
		return x.CpuUsed
	}
	return 0
}

func (x *MainIndicator) GetRamUsed() float32 {
	if x != nil {
		return x.RamUsed
	}
	return 0
}

func (x *MainIndicator) GetDiskUsed() float32 {
	if x != nil {
		return x.DiskUsed
	}
	return 0
}

func (x *MainIndicator) GetCountProject() int64 {
	if x != nil {
		return x.CountProject
	}
	return 0
}

func (x *MainIndicator) GetCountProblem() int64 {
	if x != nil {
		return x.CountProblem
	}
	return 0
}

var File_domain_server_proto protoreflect.FileDescriptor

const file_domain_server_proto_rawDesc = "" +
	"\n" +
	"\x13domain/server.proto\x12\x06domain\x1a\x1fgoogle/protobuf/timestamp.proto\"\x1a\n" +
	"\bServerID\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id\"\xba\x02\n" +
	"\rMainIndicator\x12\x1f\n" +
	"\vname_server\x18\x01 \x01(\tR\n" +
	"nameServer\x12,\n" +
	"\x06status\x18\x02 \x01(\x0e2\x14.domain.ServerStatusR\x06status\x12=\n" +
	"\flast_connect\x18\x03 \x01(\v2\x1a.google.protobuf.TimestampR\vlastConnect\x12\x19\n" +
	"\bcpu_used\x18\x04 \x01(\x02R\acpuUsed\x12\x19\n" +
	"\bram_used\x18\x05 \x01(\x02R\aramUsed\x12\x1b\n" +
	"\tdisk_used\x18\x06 \x01(\x02R\bdiskUsed\x12#\n" +
	"\rcount_project\x18\a \x01(\x03R\fcountProject\x12#\n" +
	"\rcount_problem\x18\b \x01(\x03R\fcountProblem*\xb4\x01\n" +
	"\fServerStatus\x12\x1d\n" +
	"\x19SERVER_STATUS_UNSPECIFIED\x10\x00\x12\x18\n" +
	"\x14SERVER_STATUS_ONLINE\x10\x01\x12\x19\n" +
	"\x15SERVER_STATUS_OFFLINE\x10\x02\x12\x19\n" +
	"\x15SERVER_STATUS_WARNING\x10\x03\x12\x19\n" +
	"\x15SERVER_STATUS_UNKNOWN\x10\x04\x12\x1a\n" +
	"\x16SERVER_STATUS_DISABLED\x10\x05BFZDgithub.com/Hodorev-Evgeny/deploy-guard-service-api/api/domain;domainb\x06proto3"

var (
	file_domain_server_proto_rawDescOnce sync.Once
	file_domain_server_proto_rawDescData []byte
)

func file_domain_server_proto_rawDescGZIP() []byte {
	file_domain_server_proto_rawDescOnce.Do(func() {
		file_domain_server_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_domain_server_proto_rawDesc), len(file_domain_server_proto_rawDesc)))
	})
	return file_domain_server_proto_rawDescData
}

var file_domain_server_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_domain_server_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_domain_server_proto_goTypes = []any{
	(ServerStatus)(0),             // 0: domain.ServerStatus
	(*ServerID)(nil),              // 1: domain.ServerID
	(*MainIndicator)(nil),         // 2: domain.MainIndicator
	(*timestamppb.Timestamp)(nil), // 3: google.protobuf.Timestamp
}
var file_domain_server_proto_depIdxs = []int32{
	0, // 0: domain.MainIndicator.status:type_name -> domain.ServerStatus
	3, // 1: domain.MainIndicator.last_connect:type_name -> google.protobuf.Timestamp
	2, // [2:2] is the sub-list for method output_type
	2, // [2:2] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_domain_server_proto_init() }
func file_domain_server_proto_init() {
	if File_domain_server_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_domain_server_proto_rawDesc), len(file_domain_server_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_domain_server_proto_goTypes,
		DependencyIndexes: file_domain_server_proto_depIdxs,
		EnumInfos:         file_domain_server_proto_enumTypes,
		MessageInfos:      file_domain_server_proto_msgTypes,
	}.Build()
	File_domain_server_proto = out.File
	file_domain_server_proto_goTypes = nil
	file_domain_server_proto_depIdxs = nil
}
